### ISSUE TITLE
can't download your pretrained model

### ISSUE THREAD

**Issue by shunnakamu** [Kali-Hac/TranSG#4]
Baidu requires a Chinese phone number, so can you upload your pre-trained model to another file-sharing platform?

**Comment by Kali-Hac** [comment]
Hi, we have uploaded the pre-trained models on Google Drive, please try downloading it via [this link](https://drive.google.com/file/d/1rRhJqu1blnTq2Uun7GypTXAQHHMAVdDW/view?usp=sharing).

**Comment by Kali-Hac** [comment]
Hi, we have uploaded the pre-trained models on Google Drive, please try downloading it via [this link](https://drive.google.com/file/d/1rRhJqu1blnTq2Uun7GypTXAQHHMAVdDW/view?usp=sharing). Sorry for the inconvenience.
